// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNH1OsYVWd-90zINd_UoKFKy2vHg3GeUM',
    appId: '1:778546418316:web:b1fc2f0f0523c4ab9521a9',
    messagingSenderId: '778546418316',
    projectId: 'shapeshift-40d1d',
    authDomain: 'shapeshift-40d1d.firebaseapp.com',
    storageBucket: 'shapeshift-40d1d.appspot.com',
    measurementId: 'G-QBR7WKBG81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WJxUo_1v_f8nXycvGlbEZXR4kcV4WPI',
    appId: '1:778546418316:android:1e7da65d31d0cb3c9521a9',
    messagingSenderId: '778546418316',
    projectId: 'shapeshift-40d1d',
    storageBucket: 'shapeshift-40d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjULQvCSQhUvHAkayWJdyGbAdKV7k9Wz0',
    appId: '1:778546418316:ios:dec435b4625bce639521a9',
    messagingSenderId: '778546418316',
    projectId: 'shapeshift-40d1d',
    storageBucket: 'shapeshift-40d1d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
